version: "3.9"

services:
  productstore-devdb:
    image: postgres:16.4-alpine3.20
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - "./.env"
    volumes:
      - "./scripts:/docker-entrypoint-initdb.d"

name: productstore-manager
